spring:
  datasource:
    url: jdbc:mysql://localhost:3306/consumer_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: kafka-consumer
server:
  port: 8082

