spring:
  datasource:
    url: jdbc:mysql://localhost:3306/producer_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: kafka-producer
server:
  port: 8081
  kafka:
    bootstrap-servers: kafka:9092

